"""initial migration

Revision ID: b8561b5abdf
Revises: None
Create Date: 2015-11-08 15:08:58.901000

"""

# revision identifiers, used by Alembic.
revision = 'b8561b5abdf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
